{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "template.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
  {{- if not (or (eq .Values.global.environment "development") (eq .Values.global.environment "test")) }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- else if (or .Values.serviceAccount.auto .Values.serviceAccount.role) }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{- include "template.safeAccountId" .Values.global.accountId -}}:role/{{ .Values.global.businessUnit }}-{{ .Values.global.environment }}-{{ .Values.global.regionCode}}_irsa_{{.Release.Namespace}}_{{ include "template.serviceAccountName" . }}
  {{- end }}
{{- end }}
{{- end }}
