{{ if .Values.mongodb.enabled }}
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Values.mongodb.host | default "mcp-registry-mongodb" }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  members: {{ .Values.mongodb.replicas | default 3 }}
  type: ReplicaSet
  version: {{ .Values.mongodb.version | default "8.0.16" | quote }}
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: {{ .Values.mongodb.user }}
      db: admin
      passwordSecretRef:
        name: {{ .Values.mongodb.existingPasswordSecret | default "my-user-password" }}
      roles:
        - name: clusterAdmin
          db: admin
        - name: root
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  {{- with .Values.global.nodeSelector }}
  statefulSet:
    spec:
      template:
        spec:
          nodeSelector:
            {{- toYaml . | nindent 12 }}
  {{- end }}
{{ end }}
