#!/usr/bin/env python3
"""
Agent Management Script for MCP Gateway Registry.

This tool provides CLI commands for managing A2A agents via the public API.
It uses JWT Bearer tokens from Keycloak for authentication via the mcp-gateway-m2m service account.

SERVICE ACCOUNT: mcp-gateway-m2m
The mcp-gateway-m2m service account is a Keycloak M2M client that provides authentication
for both MCP server management and A2A agent management operations. The JWT token from this
account is automatically loaded from .oauth-tokens/ingress.json.

PERMISSIONS:
- Token scopes: mcp-servers-restricted/*, mcp-servers-unrestricted/*, a2a-agent-admin
- Agent operations: register, modify, delete, list (full admin access)
- Group assignment: mcp-servers-unrestricted, a2a-agent-admin

Usage:
    # Automatically loads token from .oauth-tokens/ingress.json (generated by credentials-provider/generate_creds.sh)
    uv run python cli/agent_mgmt.py list
    uv run python cli/agent_mgmt.py get /code-reviewer
    uv run python cli/agent_mgmt.py test /code-reviewer
    uv run python cli/agent_mgmt.py test-all

For agent creation, registration, toggle, and delete operations, the mcp-gateway-m2m
service account must be assigned to the a2a-agent-admin group in Keycloak.
"""

import argparse
import json
import logging
import os
import sys
from pathlib import Path
from typing import Any, Dict, Optional
from urllib.parse import quote

import requests

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s,p%(process)s,{%(filename)s:%(lineno)d},%(levelname)s,%(message)s",
)
logger = logging.getLogger(__name__)

DEFAULT_BASE_URL: str = "http://localhost"
DEFAULT_TOKEN_FILE: str = ".oauth-tokens/ingress.json"
REQUEST_TIMEOUT: int = 10
API_VERSION: str = "v0.1"


def _load_token(token_file: str) -> str:
    """Load JWT token from file."""
    import os
    abs_path = os.path.abspath(token_file)
    try:
        with open(abs_path) as f:
            data = json.load(f)
            token = data.get("access_token") or data.get("token")
            if not token:
                raise ValueError("No access_token found in token file")
            logger.info(f"✓ Token loaded from: {abs_path}")
            logger.info(f"  Token length: {len(token)} characters")
            # Log token prefix for debugging (first 50 chars + ...)
            logger.debug(f"  Token prefix: {token[:50]}...")
            return token
    except FileNotFoundError:
        logger.error(f"✗ Token file not found: {abs_path}")
        logger.error(f"  Current directory: {os.getcwd()}")
        logger.error(f"  Looking for: {abs_path}")
        raise FileNotFoundError(f"Token file not found: {abs_path}")
    except json.JSONDecodeError as e:
        logger.error(f"✗ Invalid JSON in token file: {abs_path}")
        logger.error(f"  Error: {e}")
        raise ValueError(f"Invalid JSON in token file: {abs_path}")


def _make_request(
    method: str,
    url: str,
    token: str,
    data: Optional[Dict[str, Any]] = None,
    timeout: int = REQUEST_TIMEOUT,
) -> requests.Response:
    """Make HTTP request with Bearer token."""
    headers = {
        "Authorization": f"Bearer {token[:50]}..." if token else "Bearer <NO_TOKEN>",
        "Content-Type": "application/json",
    }

    logger.info(f"HTTP {method} Request:")
    logger.info(f"  URL: {url}")
    logger.info(f"  Headers:")
    logger.info(f"    Authorization: Bearer {token[:50]}..." if token else f"    Authorization: <NO_TOKEN>")
    logger.info(f"    Content-Type: application/json")
    if data:
        logger.info(f"  Request Body: {len(json.dumps(data))} bytes")
        logger.debug(f"  Request Data: {json.dumps(data, indent=2)}")
    logger.info(f"  Timeout: {timeout}s")

    headers["Authorization"] = f"Bearer {token}"

    try:
        logger.info(f"→ Sending {method} request to {url}...")
        response = requests.request(
            method=method,
            url=url,
            json=data,
            headers=headers,
            timeout=timeout,
        )

        # Log response details
        logger.info(f"← Received HTTP {response.status_code}")
        logger.info(f"  Response Headers:")
        for header_name, header_value in response.headers.items():
            # Hide sensitive headers
            if header_name.lower() in ['authorization', 'x-scopes']:
                logger.info(f"    {header_name}: {header_value[:50]}..." if len(str(header_value)) > 50 else f"    {header_name}: {header_value}")
            else:
                logger.info(f"    {header_name}: {header_value}")

        response_size = len(response.content) if response.content else 0
        logger.info(f"  Response Body: {response_size} bytes")

        if response.status_code >= 400:
            logger.warning(f"✗ HTTP {response.status_code} Error")
            try:
                resp_json = response.json()
                logger.warning(f"  Error Response: {json.dumps(resp_json, indent=2)}")
            except json.JSONDecodeError:
                logger.warning(f"  Error Response (raw): {response.text[:200]}")
        else:
            logger.info(f"✓ HTTP {response.status_code} Success")

        return response

    except requests.exceptions.Timeout as e:
        logger.error(f"✗ Request timed out after {timeout}s: {url}")
        logger.error(f"  Error: {e}")
        raise TimeoutError(f"Request timed out after {timeout} seconds: {url}")
    except requests.exceptions.ConnectionError as e:
        logger.error(f"✗ Failed to connect to {url}")
        logger.error(f"  Error: {e}")
        logger.error(f"  Check if service is running at {url}")
        raise ConnectionError(f"Failed to connect to {url}: {e}")
    except requests.exceptions.RequestException as e:
        logger.error(f"✗ Request failed: {e}")
        raise RuntimeError(f"Request failed: {e}")


def _print_response(response: requests.Response) -> None:
    """Pretty print response."""
    try:
        data = response.json()
        print(json.dumps(data, indent=2))
    except json.JSONDecodeError:
        print(response.text)


def list_agents(
    base_url: str,
    token: str,
) -> None:
    """List all agents via public API."""
    endpoint = f"{base_url}/{API_VERSION}/agents"
    logger.info(f"Listing all agents from {endpoint}...")

    try:
        response = _make_request("GET", endpoint, token)

        if response.status_code == 200:
            data = response.json()
            servers = data.get("servers", [])
            metadata = data.get("metadata", {})
            count = metadata.get("count", 0)

            if servers:
                print(f"Found {count} agent(s):")
                print("-" * 80)
                for server in servers:
                    name = server.get("name", "unknown")
                    description = server.get("description", "")
                    version = server.get("version", "1.0.0")
                    print(f"  {name:40} | v{version}")
                    if description:
                        print(f"    {description[:70]}")
                print("-" * 80)

                next_cursor = metadata.get("nextCursor")
                if next_cursor:
                    print(f"Next page available. Use cursor: {next_cursor}")
            else:
                print("No agents found")
        elif response.status_code == 401:
            print("Error: Authentication failed (401)")
            print("Make sure your JWT token is valid and not expired")
        else:
            print(f"Error: HTTP {response.status_code}")
            _print_response(response)

    except (TimeoutError, ConnectionError, RuntimeError) as e:
        print(f"Error: {e}")
        sys.exit(1)


def get_agent(
    base_url: str,
    token: str,
    agent_path: str,
) -> None:
    """Get agent details via public API."""
    # Convert internal path to public name: /code-reviewer -> io.mcpgateway/code-reviewer
    if agent_path.startswith("/"):
        agent_path = agent_path[1:]

    agent_name = f"io.mcpgateway/{agent_path}"
    encoded_name = quote(agent_name, safe="")
    endpoint = f"{base_url}/{API_VERSION}/agents/{encoded_name}/versions/latest"

    logger.info(f"Getting agent details for '{agent_name}'...")

    try:
        response = _make_request("GET", endpoint, token)

        if response.status_code == 200:
            print(f"Agent: {agent_name}")
            _print_response(response)
        elif response.status_code == 404:
            print(f"Error: Agent '{agent_name}' not found")
        elif response.status_code == 401:
            print("Error: Authentication failed (401)")
        else:
            print(f"Error: HTTP {response.status_code}")
            _print_response(response)

    except (TimeoutError, ConnectionError, RuntimeError) as e:
        print(f"Error: {e}")
        sys.exit(1)


def test_agent(
    base_url: str,
    token: str,
    agent_path: str,
) -> None:
    """Test agent accessibility via public API."""
    # Convert internal path to public name
    if agent_path.startswith("/"):
        agent_path = agent_path[1:]

    agent_name = f"io.mcpgateway/{agent_path}"
    encoded_name = quote(agent_name, safe="")
    endpoint = f"{base_url}/{API_VERSION}/agents/{encoded_name}/versions/latest"

    logger.info(f"Testing agent '{agent_name}'...")

    try:
        response = _make_request("GET", endpoint, token)

        if response.status_code == 200:
            data = response.json()
            server = data.get("server", {})
            name = server.get("name")
            description = server.get("description", "")

            print(f"Agent: {name}")
            print(f"Status: ACCESSIBLE")
            print(f"Description: {description}")
            print("\nFull details:")
            _print_response(response)
        elif response.status_code == 404:
            print(f"Error: Agent '{agent_name}' not found or disabled")
        elif response.status_code == 401:
            print("Error: Authentication failed (401)")
        else:
            print(f"Error: HTTP {response.status_code}")
            _print_response(response)

    except (TimeoutError, ConnectionError, RuntimeError) as e:
        print(f"Error: {e}")
        sys.exit(1)


def test_all_agents(
    base_url: str,
    token: str,
) -> None:
    """Test all agents accessibility."""
    endpoint = f"{base_url}/{API_VERSION}/agents"
    logger.info("Testing all agents...")

    try:
        response = _make_request("GET", endpoint, token)

        if response.status_code == 200:
            data = response.json()
            servers = data.get("servers", [])

            if not servers:
                print("No agents to test")
                return

            passed = 0
            failed = 0

            print("Testing agents:")
            print("-" * 80)

            for server in servers:
                name = server.get("name", "unknown")
                version = server.get("version", "1.0.0")
                print(f"[PASS] {name:40} | v{version}")
                passed += 1

            print("-" * 80)
            print(f"Summary: {passed} passed, {failed} failed")
        elif response.status_code == 401:
            print("Error: Authentication failed (401)")
        else:
            print(f"Error: HTTP {response.status_code}")
            _print_response(response)

    except (TimeoutError, ConnectionError, RuntimeError) as e:
        print(f"Error: {e}")
        sys.exit(1)


def register_agent(
    base_url: str,
    token: str,
    agent_file: str,
) -> None:
    """Register agent from JSON file via internal API."""
    import os

    abs_agent_file = os.path.abspath(agent_file)
    logger.info(f"Loading agent file from: {abs_agent_file}")

    try:
        with open(abs_agent_file) as f:
            agent_data = json.load(f)
        logger.info(f"✓ Agent file loaded successfully")
    except FileNotFoundError:
        logger.error(f"✗ Agent file not found: {abs_agent_file}")
        print(f"Error: File not found: {abs_agent_file}")
        sys.exit(1)
    except json.JSONDecodeError as e:
        logger.error(f"✗ Invalid JSON in file: {abs_agent_file}")
        logger.error(f"  Error: {e}")
        print(f"Error: Invalid JSON in file: {abs_agent_file}")
        sys.exit(1)

    # Use internal API endpoint for registration (direct to FastAPI)
    # Note: This bypasses Nginx and goes directly to :7860
    endpoint = f"{base_url}/api/agents/register"
    agent_name = agent_data.get("name", "Unknown")

    logger.info(f"=" * 80)
    logger.info(f"AGENT REGISTRATION REQUEST")
    logger.info(f"=" * 80)
    logger.info(f"Base URL: {base_url}")
    logger.info(f"Endpoint: {endpoint}")
    logger.info(f"Agent Name: {agent_name}")
    logger.info(f"Agent Path: {agent_data.get('path', 'N/A')}")
    logger.info(f"Agent File: {abs_agent_file}")
    logger.info(f"=" * 80)

    try:
        response = _make_request("POST", endpoint, token, agent_data)

        if response.status_code == 201:
            logger.info(f"✓ Agent '{agent_name}' registered successfully!")
            print(f"Agent '{agent_name}' registered successfully!")
            _print_response(response)
        elif response.status_code == 401:
            logger.error(f"✗ Authentication failed (HTTP 401)")
            logger.error(f"  Token file location: {os.path.abspath('.oauth-tokens/ingress.json')}")
            logger.error(f"  Token length: {len(token) if token else 0} characters")
            logger.error(f"  Authorization header: Bearer {token[:50]}..." if token else "  Authorization header: <NO_TOKEN>")
            print("Error: Authentication failed (HTTP 401)")
            print("\nDEBUG INFORMATION:")
            print(f"  Token file: {os.path.abspath('.oauth-tokens/ingress.json')}")
            print(f"  Token length: {len(token) if token else 0} characters")
            print("\nNOTE: Make sure you have a valid token in '.oauth-tokens/ingress.json'")
            print("  The token should contain 'a2a-agent-admin' in groups claim")
            print("  Regenerate with: ./credentials-provider/generate_creds.sh")
            print("\nRESPONSE:")
            _print_response(response)
        elif response.status_code == 409:
            path = agent_data.get("path", "unknown")
            print(f"Error: Agent with path '{path}' already exists")
            _print_response(response)
        elif response.status_code == 422:
            print("Error: Validation failed - check agent JSON format")
            _print_response(response)
        elif response.status_code == 403:
            print("Error: Permission denied. You do not have permission to register agents")
            print("\nNote: Agent registration requires proper Keycloak authentication with 'register_service' permission.")
            print("For testing/development, you may need to:")
            print("  1. Configure a Keycloak user with appropriate permissions")
            print("  2. Use the web UI dashboard to register agents")
            print("  3. Contact your administrator to grant registration permissions")
            _print_response(response)
        else:
            print(f"Error: HTTP {response.status_code}")
            _print_response(response)

    except (TimeoutError, ConnectionError, RuntimeError) as e:
        print(f"Error: {e}")
        sys.exit(1)


def main() -> None:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Agent Management Script for MCP Gateway Registry - Public API",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Start the registry service (run in another terminal)
  python -m uvicorn registry.main:app --reload

  # Register an agent from JSON file
  export TOKEN="test-token"
  uv run python cli/agent_mgmt.py register cli/examples/test_code_reviewer_agent.json

  # List all agents
  uv run python cli/agent_mgmt.py list

  # Get agent details
  uv run python cli/agent_mgmt.py get /test-reviewer

  # Test agent accessibility
  uv run python cli/agent_mgmt.py test /test-reviewer

  # Test all agents
  uv run python cli/agent_mgmt.py test-all

For more information on creating agent JSON files:
  cat cli/examples/README.md
  cat .scratchpad/A2A_AGENT_CLI_REGISTRATION_GUIDE.md

Note: For agent deletion, use the web UI or administrative CLI tools.
This script provides discovery, testing, and registration functionality.
""",
    )

    parser.add_argument(
        "--base-url",
        default=DEFAULT_BASE_URL,
        help=f"Base URL for API (default: {DEFAULT_BASE_URL})",
    )
    parser.add_argument(
        "--token-file",
        default=DEFAULT_TOKEN_FILE,
        help=f"Path to token JSON file (default: {DEFAULT_TOKEN_FILE})",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug logging",
    )

    subparsers = parser.add_subparsers(dest="command", help="Command to execute")

    # Register command
    register_parser = subparsers.add_parser("register", help="Register agent from JSON file")
    register_parser.add_argument("file", help="Path to agent JSON file")

    # List command
    subparsers.add_parser("list", help="List all agents")

    # Get command
    get_parser = subparsers.add_parser("get", help="Get agent details")
    get_parser.add_argument("path", help="Agent path (e.g., /code-reviewer)")

    # Test command
    test_parser = subparsers.add_parser("test", help="Test agent accessibility")
    test_parser.add_argument("path", help="Agent path (e.g., /code-reviewer)")

    # Test all command
    subparsers.add_parser("test-all", help="Test all agents")

    args = parser.parse_args()

    if args.debug:
        logger.setLevel(logging.DEBUG)

    if not args.command:
        parser.print_help()
        sys.exit(1)

    # Load token
    try:
        token = _load_token(args.token_file)
    except (FileNotFoundError, ValueError) as e:
        print(f"Error: {e}")
        sys.exit(1)

    # Execute command
    if args.command == "list":
        list_agents(args.base_url, token)
    elif args.command == "get":
        get_agent(args.base_url, token, args.path)
    elif args.command == "test":
        test_agent(args.base_url, token, args.path)
    elif args.command == "test-all":
        test_all_agents(args.base_url, token)
    elif args.command == "register":
        register_agent(args.base_url, token, args.file)


if __name__ == "__main__":
    main()
