{{- $hasSecretEnvs := false }}
{{- $ssmRegex := "^ssm:" }}
{{- range $key, $value := .Values.config.envs }}
{{- if regexMatch $ssmRegex $value }}
{{- $hasSecretEnvs = true }}
{{- end }}
{{- end }}
{{- if or $hasSecretEnvs .Values.config.secretFiles }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "template.fullname" . }}-external-secrets
  namespace: {{ .Release.Namespace }}
spec:  
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.config.secretStoreRef.name }}
    kind: {{ .Values.config.secretStoreRef.kind }}
  target:
    name: {{ include "template.fullname" . }}-external-secrets
    creationPolicy: Owner
    {{- if .Values.config.secretFiles }}
    template:
      data:
        {{- range .Values.config.secretFiles }}
        {{ .name }}: |
          {{- $params := dict "Input" (.value | toYaml) "Regex" (include "template.searchString" .) }}
          {{- $params | include "template.regexFindAndReplaceAll" | nindent 10 }}
        {{- end }}
    {{- end }}
  data:
  {{- $regex := "^ssm:[^/]*" -}}
  {{- $replacement := "" -}}
  {{- $values := regexFindAll (include "template.searchString" .) (toYaml .Values.config.secretFiles | toString) -1 | uniq }}
  {{- range $values }}
    - secretKey: {{ include "template.hashString" . | printf "SECRET_REF_%s" }}
      remoteRef:
        key: {{ regexReplaceAll $regex . $replacement }}
  {{- end }}
  {{- range $key, $value := .Values.config.envs }}
  {{- if regexMatch $regex $value }}
    - secretKey: {{ include "template.hashString" $key | printf "SECRET_REF_%s" }}
      remoteRef:
        key: {{ regexReplaceAll $regex $value $replacement }}
  {{- end }}
  {{- end }}
{{- end }}