# Default values for application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1

image:
  repository: starter-app # autogenerates repo path for local & aws envs
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

observability:
  otlp_endpoint: http://jaeger-collector.observabililty-system:4318

local:
  aws:
    endpoint_url: http://localstack.aws-system:4566
    access_key_id: test
    secret_access_key: test

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  auto: false

statsdExporter:
  enabled: false
  env:
    - name: SKIP_KYVERNO
      value: "true"
  image:
    repository: prom/statsd-exporter
    tag: v0.28.0
    pullPolicy: IfNotPresent
  livenessProbe:
    httpGet:
      path: /-/healthy
      port: statsd
    initialDelaySeconds: 30
    timeoutSeconds: 1
    failureThreshold: 3
    periodSeconds: 15
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /-/ready
      port: statsd
    initialDelaySeconds: 30
    timeoutSeconds: 1
    failureThreshold: 3
    periodSeconds: 15
    successThreshold: 1
  resources:
    requests:
      cpu: 12m
      memory: 132M
    limits:
      cpu: 20m
      memory: 132M

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

service:
  healthCheck: /health
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: "nginx"
  annotations: []
  hosts: [] # autogenerated: zme-webapp.eks-local.zmp-development-use1.zetaglobal.io
  extraPaths:
    - path: /
      pathType: ImplementationSpecific
    - path: /*
      pathType: ImplementationSpecific
  tls: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

probes:
  liveness:
    httpGet:
      path: /health
      port: http
    periodSeconds: 60
    timeoutSeconds: 30
  readiness:
    httpGet:
      path: /health
      port: http
    periodSeconds: 60
    timeoutSeconds: 30

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  pollingInterval: 30

nodeSelector: {}

tolerations: []

affinity: {}

topology:
  hostSkew: 1
  nodeSkew: 1
  
karpenter:
  nodeClass:
    ami: bottlerocket@latest
  nodePool:
    limits:
      cpu: 64 # up to 16x 4C instances
    labels:
      opentelemetry.io/enabled: "true"
    capacityType:
      operator: In
      values:
        - spot
        - on-demand
    kubernetes:
      arch:
        operator: In
        values:
          - arm64
          - amd64
      os:
        operator: In
        values:
          - linux
    instance:
      hypervisor:
        operator: In
        values:
          - nitro
      category:
        operator: In
        values:
          - c
          - m
          - r
          - x
      cpu:
        operator: Gt
        values:
          - "1"
      generation:
        operator: Gt
        values:
          - "5"

serviceMonitor:
  enabled: false

config:
  secretStoreRef:
    name: k8s-read-paramstore
    kind: ClusterSecretStore

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

pdb: # only min or max can be used, not both
  enabled: true
  #minAvailable: 1
  maxUnavailable: 1
