---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mcp-gateway-registry-local
  namespace: assistants
spec:
  secretRef:
    name: ecr-credentials
  type: oci
  interval: 60m0s
  url: oci://636347950933.dkr.ecr.us-east-1.amazonaws.com/zeta-aiml/gen-ai/ai-assistants/mcp-gateway-registry/charts
  provider: aws
